services:
  - type: web
    name: kites-laravel
    env: docker
    plan: free
    branch: main
    envVars:
      - key: APP_KEY
        value: base64:3r1sXEnUgADozxjeFTHv16/c+xTwIFO4nvEny86hUSA=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4in3c4hg0os73a25f2g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: krunal_postgres
      - key: DB_USERNAME
        value: krunal_postgres_user
      - key: DB_PASSWORD
        value: W78LvfrmDRW5I5rPmhrSPLc722ghM2fY
